---
- name: Checkout dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/dgokcin/dotfiles.git'
    dest: ~/codes/dotfiles
    version: master

# Pass in extra arguments to build
- name: Run make on the dotfiles repo.
  community.general.make:
    chdir: ~/codes/dotfiles
    target: personal
