---
- name: Checkout dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/dgokcin/dotfiles.git'
    force: yes
    dest: ~/codes/dotfiles
    version: master

# Pass in extra arguments to build
- name: Run 'install' target as root
  community.general.make:
    chdir: ~/codes/dotfiles
    target: personal
